### ISSUE TITLE
Juicer cart promote should pull cart if not present

### ISSUE THREAD

**Issue by Jmainguy** [juicer/juicer#231]
juicer cart promote rhsmweb_chg6602
error: an error occured while accessing /home/rdu/jmainguy/.config/juicer/carts/rhsmweb_chg6602:
Juicer error happened:
Could not find file: '/home/rdu/jmainguy/.config/juicer/carts/rhsmweb_chg6602.json'

Instead of spitting an error, it should pull the cart if the file is not found, and then spit an error if the pull fails (cart doesn't exist)

**Comment by yithian** [comment]
I have this dream where all operations would operate on the version of the cart stored in the db (like this) unless the local copy is newer.

/me checks his calendar

**Comment by tbielawa** [comment]
Alex. We don't have time for dreams where we're going
